
all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/bootcamp.pem

    regenerate_keystore_and_truststore: true
    jmxexporter_enabled: true

    region: emea

    ssl_enabled: true
    ssl_provided_keystore_and_truststore: true
    ssl_keystore_filepath: "/home/ubuntu/ssl/{{inventory_hostname}}-keystore.jks"
    ssl_keystore_key_password: changeme
    ssl_keystore_store_password: changeme
    ssl_truststore_filepath: "/home/ubuntu/ssl/kafka-truststore.jks"
    ssl_truststore_password: changeme
    ssl_truststore_ca_cert_alias: root-ca

    ssl_mutual_auth_enabled: true
    zookeeper_quorum_authentication_type: mtls
    zookeeper_client_authentication_type: digest

    #
    # Kerberos settings
    #
    kerberos_kafka_broker_primary: kafka
    kerberos_configure: true
    kerberos:
      realm: "BOOTCAMP-{{region | upper}.CONFLUENT.IO"
      kdc_hostname: "samba.bootcamp-emea.confluent.io"
      admin_hostname: "samba.bootcamp-emea.confluent.io"
      canonicalize: false
      # sasl_protocol: kerberos

    zookeeper_kerberos_keytab_path: "/home/ubuntu/kerberos/zookeeper-{{inventory_hostname_short}}.keytab"
    zookeeper_kerberos_principal: "zookeeper/{{inventory_hostname}}@{{kerberos.realm | upper}}"
    kafka_broker_kerberos_keytab_path: "/home/ubuntu/kerberos/kafka-{{inventory_hostname_short}}.keytab"
    kafka_broker_kerberos_principal: "kafka/{{inventory_hostname}}@{{kerberos.realm | upper}}"
    schema_registry_kerberos_keytab_path: "/home/ubuntu/kerberos/schema-registry-{{inventory_hostname_short}}.keytab"
    schema_registry_kerberos_principal: "schema-registry/{{inventory_hostname}}@{{kerberos.realm | upper}}"
    kafka_rest_kerberos_keytab_path: "/home/ubuntu/kerberos/rest-{{inventory_hostname_short}}.keytab"
    kafka_rest_kerberos_principal: "rest/{{inventory_hostname}}@{{kerberos.realm | upper}}"
    kafka_connect_kerberos_keytab_path: "/home/ubuntu/kerberos/kafka-connect-{{inventory_hostname_short}}.keytab"
    kafka_connect_kerberos_principal: "kafka-connect/{{inventory_hostname}}@{{kerberos.realm | upper}}"
    ksql_kerberos_keytab_path: "/home/ubuntu/kerberos/ksqldb-{{inventory_hostname_short}}.keytab"
    ksql_kerberos_principal: "ksqldb/{{inventory_hostname}}@{{kerberos.realm | upper}}"
    control_center_kerberos_keytab_path: "/home/ubuntu/kerberos/control-center-{{inventory_hostname_short}}.keytab"
    control_center_kerberos_principal: "control-center/{{inventory_hostname}}@{{kerberos.realm | upper}}"

    # RBAC settings
    #
    rbac_enabled: true
    rbac_component_additional_system_admins: [ alice ]
    mds_super_user: mds
    mds_super_user_password: mds-secret
    kafka_broker_ldap_user: kafka
    kafka_broker_ldap_password: kafka-secret
    schema_registry_ldap_user: schemaregistry
    schema_registry_ldap_password: schema-secret
    kafka_connect_ldap_user: connect
    kafka_connect_ldap_password: connect-secret
    ksql_ldap_user: ksql
    ksql_ldap_password: ksql-secret
    kafka_rest_ldap_user: rest
    kafka_rest_ldap_password: rest-secret
    control_center_ldap_user: controlcenter
    control_center_ldap_password: c3-secret

    sasl_scram_users:
      alice:
        principal: alice
        password: alice-secret
      charlie:
        principal: charlie
        password: charlie-secret

    kafka_broker_custom_listeners:
      broker:
        name: BROKER
        port: 9091
        ssl_enabled: true
        ssl_mutual_auth_enabled: false
        sasl_protocol: kerberos
      internal:
        name: INTERNAL
        port: 9092
        ssl_enabled: true
        ssl_mutual_auth_enabled: false
        sasl_protocol: oauth
      client_listener:
        name: CLIENT
        port: 9093
        ssl_enabled: true
        ssl_mutual_auth_enabled: true
      ldap_listener:
        name: LDAP
        port: 9094
        ssl_enabled: true
        ssl_mutual_auth_enabled: false
        sasl_protocol: plain
      scram_listener:
        name: SCRAM
        port: 9095
        ssl_enabled: true
        ssl_mutual_auth_enabled: true
        sasl_protocol: scram
